# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9120090814534f05f4a627a65c6f6f62"
name = "new-test-app"
handle = "new-test-app-146"
application_url = "https://jvc-impression-remix-str.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-app-devit.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://jvc-impression-remix-str.trycloudflare.com/auth/callback",
  "https://jvc-impression-remix-str.trycloudflare.com/auth/shopify/callback",
  "https://jvc-impression-remix-str.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
